services:
  - type: web
    name: water-platform
    runtime: java
    repo: https://github.com/PahanIvan2007/kayran-Java.git
    branch: master
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/water-platform-0.0.1-SNAPSHOT.jar
    healthCheckPath: /auth/login
    envVars:
      - key: PORT
        value: 10000
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64
